from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(483, 407)
        Form.setMinimumSize(QtCore.QSize(483, 407))
        Form.setMaximumSize(QtCore.QSize(484, 407))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Path .ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background: rgb(26, 26, 29);\n"
"")
        self.main_menu = QtWidgets.QWidget(Form)
        self.main_menu.setGeometry(QtCore.QRect(0, 0, 481, 411))
        self.main_menu.setObjectName("main_menu")
        self.label_4 = QtWidgets.QLabel(self.main_menu)
        self.label_4.setGeometry(QtCore.QRect(170, 30, 171, 21))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Path .ico"))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.main_menu)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 190, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 78, 80);\n"
"border-radius: 5px;")
        self.lineEdit_4.setMaxLength(900)
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.main_menu)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 270, 101, 51))
        self.pushButton_4.setStyleSheet("color: rgb(168, 21, 36)")
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget_2 = QtWidgets.QWidget(self.main_menu)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 61, 411))
        self.widget_2.setStyleSheet("background-color: rgba(0, 0, 0, 30) ")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 360, 41, 41))
        self.pushButton_3.setStyleSheet("background: rgb(26, 26, 29);\n"
"background-image: url(\"Path to background\");")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Path to exit .ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(41, 41))
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.main_menu)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 100, 75, 23))
        self.pushButton_5.setStyleSheet("color: rgb(168, 21, 36)")
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.main_menu)
        self.label_6.setGeometry(QtCore.QRect(90, 70, 111, 21))
        self.label_6.setStyleSheet("color: rgb(111, 34, 50);")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.main_menu)
        self.label_5.setGeometry(QtCore.QRect(90, 150, 131, 21))
        self.label_5.setStyleSheet("color: rgb(111, 34, 50);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.main_menu)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(6)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 78, 80);\n"
"border-radius: 5px;")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.main_menu)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 270, 101, 51))
        self.pushButton_6.setStyleSheet("color: rgb(168, 21, 36)")
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.menu_register = QtWidgets.QWidget(self.main_menu)
        self.menu_register.setEnabled(True)
        self.menu_register.setGeometry(QtCore.QRect(60, 0, 481, 411))
        self.menu_register.setMinimumSize(QtCore.QSize(481, 411))
        self.menu_register.setMaximumSize(QtCore.QSize(481, 411))
        self.menu_register.setAcceptDrops(False)
        self.menu_register.setAccessibleDescription("")
        self.menu_register.setStyleSheet("")
        self.menu_register.setObjectName("menu_register")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.menu_register)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 130, 151, 31))
        self.lineEdit_5.setStyleSheet("border-radius: 1px;\n"
"border-radius: 5px;\n"
"color: rgb(255,255,255);\n"
"background-color: rgb(78, 78, 80);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.menu_register)
        self.label_7.setGeometry(QtCore.QRect(160, 170, 61, 21))
        self.label_7.setStyleSheet("color: rgb(111, 34, 50);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.menu_register)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 200, 151, 31))
        self.lineEdit_6.setStyleSheet("border-radius: 1px;\n"
"border-radius: 5px;\n"
"color: rgb(255,255,255);\n"
"background-color: rgb(78, 78, 80);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.menu_register)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 250, 71, 41))
        self.pushButton_7.setStyleSheet("color: rgb(168, 21, 36);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.menu_register)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 250, 71, 41))
        self.pushButton_8.setStyleSheet("color: rgb(168, 21, 36);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_8 = QtWidgets.QLabel(self.menu_register)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(195, 7, 63);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.menu_register)
        self.label_9.setGeometry(QtCore.QRect(160, 100, 61, 21))
        self.label_9.setStyleSheet("color: rgb(111, 34, 50);")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Menu"))
        self.pushButton_4.setText(_translate("Form", "Encrypt"))
        self.pushButton_5.setText(_translate("Form", "Choose"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#a81524;\">File:</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#a81524;\">Your token (key):</span></p></body></html>"))
        self.pushButton_6.setText(_translate("Form", "Decrypt"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#a81524;\">Password</span></p></body></html>"))
        self.pushButton_7.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_7.setText(_translate("Form", "Sign-in"))
        self.pushButton_8.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_8.setText(_translate("Form", "Sign-up"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#c3073f;\">Sing in</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#a81524;\">Login</span></p></body></html>"))
